---
title: "Installing libraries"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

These packages need to be installed for the course:


```{r}
options(repos = c(CRAN = "https://cloud.r-project.org")) # HT: fyGuo
install.packages("devtools") # Package management tools
install.packages("tidyverse") # Tidy data
install.packages("dplyr") # Data manipulation
install.packages("ggplot2") # Data visualization
install.packages("dslabs") # Datasets
install.packages("rafalib") # Data exploration
install.packages("rmarkdown") # Rmarkdown
install.packages("knitr") # Report generation
install.packages("tableone") # Summary statistics
install.packages("glmnet") # Generalized linear models
install.packages("GGally") # Grammar of graphics
install.packages("tree") # Tree models
install.packages("randomForest") # Random forests
install.packages("caret") # Models
install.packages("cluster") # Clustering
install.packages("pROC") # Evaluation
install.packages("ROCR") # Evaluation
install.packages("tidymodels") # Workflows
install.packages("ollamar")
```
